spring:
  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost/cobranca
    username: root
    password: SYSADM
  jpa:
    database: 
    hibernate:
      ddl-auto: update
#    driver-class-name: org.h2.Driver
#    platform: h2
 
  # enable H2 web console and set url for web console
  # http://localhost:8080/console
#  h2:
#    console:
#      enabled: true
#      path: /console